name: Lint KubeJS
on:
  pull_request:
    types: [opened, synchronize]
    paths: 
      - 'kubejs/**'
permissions:
  contents: read
jobs:
  lint:
    uses: ./.github/workflows/eslint.yml
    with:
      folder: 'kubejs'

  comment:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - if: needs.lint.outputs.outcome == 'failure'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚠️ Warning: [the latest commit "${{ github.event.pull_request.head.label }}"](https://github.com/${{github.event.pull_request.base.repo.owner.name}}/${{github.event.pull_request.base.repo.name}}/commit/${{github.event.pull_request.head.sha}}) **does not pass ESLint**!'
            })
